org.gradle.jvmargs=-Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.4.101-hotspot
mod_version=1.0
modmenu_version=11.0.3
cloth_config_version=15.0.140
loomx.loom_version=1.18-SNAPSHOT
loader_version=0.19.5
